### ISSUE TITLE
UIAlertView causes NSInvalidArgumentException (incompatible signatures)

### ISSUE THREAD

**Issue by phaitour** [zwaldowski/BlocksKit#260]
I'm experiencing an intermittent bug when showing UIAlertView's through blockskit's shortcut `bk_showAlertViewWithTitle:...`.  The crash:

    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempted to create block invocation with incompatible signatures'

If you comment out the lines 177-179 in A2BlockInvocation.m, then everything works fine.  It seems to be more prevalent in older generation phones (iphone 4/4s, iphone 5...).  Could this have something to do with how `isSignature:compatibleWithSignature:` works on 32 bit devices vs 64 bit devices?

As for whether or not the block signatures are actually incorrect... I've triple checked every single one and they're correct.

**Comment by eikebartels** [comment]
Any news on this side? The issue still exist

**Comment by hiltonc** [comment]
Just ran into this.

**Comment by DanielKrofchick** [comment]
To give some colour. We only see this issue when running on iPad.
