### ISSUE TITLE
Swift version?

### ISSUE THREAD

**Issue by klaas** [zwaldowski/BlocksKit#263]
I read, that there might be an upcoming Swift version? Maybe a ClosuresKit? Does someone know where it can be found?

**Comment by klaas** [comment]
Just noticed your comment. Feel free to use the name ;-)

**Comment by johndpope** [comment]
https://github.com/britzlieg/ClosuresKit

**Comment by johndpope** [comment]
Just came across some code using a react pattern on uitextfield.  - https://github.com/Ramotion/reel-search - what's the best way to hook into delegate methods with swift? 
  let tf = UIView()
   tf.onTap = {}

 fyi - http://objc2swift.yahoo-labs.jp/

**Comment by johndpope** [comment]
this seems to be the best replacement thus far for blocks in swift.
https://github.com/collinhundley/APTargets
